exports.up = knex =>
    knex.schema.createTable('games', table => {
        table.increments('id')
            .primary()
            .unique()
            .notNullable()
        table.varchar('name', 16)
            .notNullable()
        table.bool('restricted')
            .notNullable()
            .defaultTo(false)
        table.smallint('max_players')
            .notNullable()
            .defaultTo(500)
        table.datetime('start_time')
            .notNullable()
        table.datetime('end_time')
            .notNullable()
        table.integer('start_turns')
            .notNullable()
        table.integer('start_reserves')
            .defaultTo(0)
        table.smallint('turn_amount')
            .notNullable()
            .defaultTo(10)
        table.integer('max_turns')
            .notNullable()
            .defaultTo(500)
        table.smallint('turn_speed')
            .notNullable()
            .defaultTo(600)
        table.smallint('max_attacks_in')
            .notNullable()
            .defaultTo(-1)
        table.smallint('max_attacks_out')
            .notNullable()
            .defaultTo(-1)
        table.smallint('max_alliance_members')
            .notNullable()
            .defaultTo(10)
    })

exports.down = knex =>
    knex.schema.dropTableIfExists('games')