exports.up = knex =>
    knex.schema.createTable('players', table => {
        table.increments('id')
            .primary()
            .unique()
            .notNullable()
        table.unique(['game', 'name'])
        table.integer('user')
            .references('id')
            .inTable('users')
            .onUpdate('CASCADE')
            .onDelete('CASCADE')
        table.integer('game')
            .references('id')
            .inTable('games')
            .onUpdate('CASCADE')
            .onDelete('CASCADE')
        table.varchar('name', 16)
            .notNullable()
        table.bigint('cash')
            .notNullable()
            .defaultTo(0)
        table.integer('turns')
            .notNullable()
            .defaultTo(0)
    })

exports.down = knex =>
    knex.schema.dropTableIfExists('players')